### ISSUE TITLE
Issue in building quant

### ISSUE THREAD

**Issue by Pallavikadam10** [NTAP/quant#7] opened 2018-01-31 17:33 UTC
Hi,

I'm trying to build the quant on Fedora. After running 'make' command, I'm facing the following issue. 
Please guide me in this. 
I already have all the header files of openssl but somehow it's unable to link them to quant/picotls. 

-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/quant/Debug/external/picotls-prefix/src/picotls-build
[  1%] Linking C executable test-openssl.t
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `sk_X509_num':
/usr/local/include/openssl/x509.h:99: undefined reference to `OPENSSL_sk_num'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `sk_X509_value':
/usr/local/include/openssl/x509.h:99: undefined reference to `OPENSSL_sk_value'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `sk_X509_free':
/usr/local/include/openssl/x509.h:99: undefined reference to `OPENSSL_sk_free'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `do_sign':
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:333: undefined reference to `EVP_MD_CTX_new'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:342: undefined reference to `RSA_pkey_ctx_ctrl'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:346: undefined reference to `RSA_pkey_ctx_ctrl'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:350: undefined reference to `RSA_pkey_ctx_ctrl'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:374: undefined reference to `EVP_MD_CTX_free'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `aead_chacha20poly1305_setup_crypto':
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:518: undefined reference to `EVP_chacha20_poly1305'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `verify_sign':
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:619: undefined reference to `EVP_MD_CTX_new'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:628: undefined reference to `RSA_pkey_ctx_ctrl'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:632: undefined reference to `RSA_pkey_ctx_ctrl'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:636: undefined reference to `RSA_pkey_ctx_ctrl'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:653: undefined reference to `EVP_MD_CTX_free'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `ptls_openssl_init_sign_certificate':
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:705: undefined reference to `EVP_PKEY_up_ref'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `ptls_openssl_init_verify_certificate':
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:846: undefined reference to `X509_STORE_up_ref'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `ptls_openssl_encrypt_ticket':
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:885: undefined reference to `HMAC_CTX_new'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:919: undefined reference to `HMAC_size'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:927: undefined reference to `EVP_CIPHER_CTX_reset'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:929: undefined reference to `HMAC_CTX_free'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `ptls_openssl_decrypt_ticket':
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:944: undefined reference to `HMAC_CTX_new'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:961: undefined reference to `HMAC_size'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:997: undefined reference to `EVP_CIPHER_CTX_reset'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/../lib/openssl.c:999: undefined reference to `HMAC_CTX_free'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `test_rsa_sign':
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/openssl.c:100: undefined reference to `EVP_PKEY_up_ref'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `test_ecdsa_sign':
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/openssl.c:124: undefined reference to `EVP_PKEY_up_ref'
CMakeFiles/test-openssl.t.dir/t/openssl.c.o: In function `main':
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/openssl.c:161: undefined reference to `OPENSSL_init_crypto'
/usr/src/quant/Debug/external/picotls-prefix/src/picotls/t/openssl.c:162: undefined reference to `OPENSSL_init_crypto'
collect2: error: ld returned 1 exit status
CMakeFiles/test-openssl.t.dir/build.make:590: recipe for target 'test-openssl.t' failed
make[5]: *** [test-openssl.t] Error 1
CMakeFiles/Makefile2:100: recipe for target 'CMakeFiles/test-openssl.t.dir/all' failed
make[4]: *** [CMakeFiles/test-openssl.t.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make[3]: *** [all] Error 2
external/CMakeFiles/picotls.dir/build.make:110: recipe for target 'external/picotls-prefix/src/picotls-stamp/picotls-build' failed
make[2]: *** [external/picotls-prefix/src/picotls-stamp/picotls-build] Error 2
CMakeFiles/Makefile2:309: recipe for target 'external/CMakeFiles/picotls.dir/all' failed
make[1]: *** [external/CMakeFiles/picotls.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Thanks,
Pallavi

**Comment by larseggert** [comment] 2018-02-01 07:50
Since you closed this, I assume you figure out the problem?

(This is actually a build issue in picoTLS.)

**Comment by Pallavikadam10** [comment] 2018-02-01 17:24
Hi,

I haven't figured it out yet. 
I have build the picoTLS separately as described in the document - [https://github.com/h2o/picotls]. 

Thanks,
Pallavi

**Comment by larseggert** [comment] 2018-02-02 07:16
quant builds picotls internally, so you don't need to build it separately.

Based on the error you see, it seems that your openssl version under `/usr/local` is maybe too old?

**Comment by Pallavikadam10** [comment] 2018-02-02 18:10
I updated the openssl. 

[root@ovsDUT ~]# openssl version
OpenSSL 1.1.1-dev  xx XXX xxxx
[root@ovsDUT ~]# openssl ciphers -v | awk '{print $2}' | sort | uniq
SSLv3
TLSv1
TLSv1.2
TLSv1.3
[root@ovsDUT ~]#

Could it be some linker error? How should I figure it out?

Thanks,

**Comment by larseggert** [comment] 2018-02-04 13:33
Is that openssl installed where quant is looking for it? If you remove the build directory and try from scratch, what does the full log show?

**Comment by Pallavikadam10** [comment] 2018-02-05 22:05
Do you mean remove the quant and build it from scratch?

**Comment by larseggert** [comment] 2018-02-06 08:42
The quant README tells you to build in a `Debug` subdirectory. I meant that you should clean out the contents of that build directory and redo the build (starting with calling `cmake`).

**Comment by larseggert** [comment] 2018-02-10 14:06
Have you managed to build quant yet?

**Comment by Pallavikadam10** [comment] 2018-02-12 20:02
I tried redoing the build. Getting following error:

[root@ovsDUT Debug]# cmake ..
-- Configuring done
CMake Error in lib/CMakeLists.txt:
  Imported target "warpcore" includes non-existent path

    "/usr/src/quant/Debug/external/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
-- Build files have been written to: /usr/src/quant/Debug
[root@ovsDUT Debug]#

**Comment by larseggert** [comment] 2018-02-12 21:39
Are you sure your `Debug` directory is empty? Because the output you post doesn't show `cmake` running from scratch.

**Comment by Pallavikadam10** [comment] 2018-02-13 17:43
Yes, I created an empty Debug dir. Following is the output:

[root@ovsDUT Debug]# cmake ..
-- The C compiler identification is GNU 6.4.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for htobe64
-- Looking for htobe64 - found
-- Looking for htobe64
-- Looking for htobe64 - not found
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2m")
-- Performing Test _march_native
-- Performing Test _march_native - Success
-- Performing Test _Wextra
-- Performing Test _Wextra - Success
-- Performing Test _Wpedantic
-- Performing Test _Wpedantic - Success
-- Performing Test _Weverything
-- Performing Test _Weverything - Failed
-- Performing Test _Werror
-- Performing Test _Werror - Success
-- Performing Test _fcolor_diagnostics
-- Performing Test _fcolor_diagnostics - Failed
-- Performing Test _fdiagnostics_color_always
-- Performing Test _fdiagnostics_color_always - Success
-- Performing Test _Wno_missing_field_initializers
-- Performing Test _Wno_missing_field_initializers - Success
-- Performing Test _Wno_disabled_macro_expansion
-- Performing Test _Wno_disabled_macro_expansion - Success
-- Performing Test _Wno_cpp
-- Performing Test _Wno_cpp - Success
-- Performing Test _Wno_missing_braces
-- Performing Test _Wno_missing_braces - Success
-- Performing Test _Wno_gnu_statement_expression
-- Performing Test _Wno_gnu_statement_expression - Success
-- Performing Test _Wno_extended_offsetof
-- Performing Test _Wno_extended_offsetof - Success
-- Looking for sanitizer/asan_interface.h
-- Looking for sanitizer/asan_interface.h - found
-- Performing Test _fsanitize_address
-- Performing Test _fsanitize_address - Success
-- Performing Test _fno_omit_frame_pointer
-- Performing Test _fno_omit_frame_pointer - Success
-- Performing Test _fsanitize_address_use_after_scope
-- Performing Test _fsanitize_address_use_after_scope - Failed
-- Performing Test _fno_optimize_sibling_calls
-- Performing Test _fno_optimize_sibling_calls - Success
-- Performing Test _fsanitize_undefined
-- Performing Test _fsanitize_undefined - Success
-- Performing Test _fsanitize_unsigned_integer_overflow
-- Performing Test _fsanitize_unsigned_integer_overflow - Failed
-- Performing Test _fno_sanitize_alignment
-- Performing Test _fno_sanitize_alignment - Success
-- Performing Test _fno_common
-- Performing Test _fno_common - Success
-- Found http-parser: /usr/lib64/libhttp_parser.so
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot
-- Found libev: /usr/lib64/libev.so
-- Configuring done
CMake Error in lib/CMakeLists.txt:
  Imported target "warpcore" includes non-existent path

    "/usr/src/quant/Debug/external/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
-- Build files have been written to: /usr/src/quant/Debug
[root@ovsDUT Debug]#

**Comment by larseggert** [comment] 2018-02-14 04:43
Thanks for the full log! Intersting, I don't see this error, because I use `ninja` to build (`-GNinja`) and not `make`. I can reproduce it with `make` locally, and I will try and fix this. (This may be a bug in cmake.)

The good new is that you should be able to ignore the cmake error and just do `make` afterwards. At least for me, it builds fine then.

**Closed** 2018-02-14 04:53 UTC
Labels: question

**Comment by Pallavikadam10** [comment] 2018-02-16 19:08
Thank you!
